CLICK_POWER = 12
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
BG_COLOUR = (0, 0, 0)
PYTHON_ICON_FILE = 'assets/pics/python_icon.png'
SCORE_FILE = 'score.txt'
FONT_NAME = None
FONT_SIZE = 30
RESET_SCORE_BUTTON_FILE = 'assets/pics/reset_score_button.png'
CLICK_SOUND_EFFECT_FILE = 'assets/sound_effects/click_sound_effect.wav'
RESET_SOUND_EFFECT_FILE = 'assets/sound_effects/reset.wav'
ONE_HUNDRED_SCORE_MARK_FILE = 'assets/sound_effects/100_score_mark.wav'
DARK_MODE_FILE = 'assets/pics/dark_mode.png'
LIGHT_MODE_FILE = 'assets/pics/light_mode.png'
LIGHT_MODE_BG_COLOUR = 'orange'
DARK_MODE_BG_COLOUR = (48, 48, 47)
DARK_LIGHT_MODE_TOGGLE_SOUND_EFFECT_FILE = 'assets/sound_effects/dark_light_mode_toggle.wav'
POWER_BUTTON_FILE = 'assets/pics/power.png'
POWER_OFF_SOUND_FILE = 'assets/sound_effects/power_off_sound.wav'
STATE_SHUTTING_DOWN = 'shutting_down'
STATE_GAME = 'game'
YES_BUTTON_FILE = 'assets/pics/yes.png'
NO_BUTTON_FILE = 'assets/pics/no.png'
STATE_SHOP = 'shop'
SHOPPING_BUTTON_FILE = 'assets/pics/shopping_trolley.png'